### PR TITLE
fix ObjectID.toHexString issue with latest bson module. Closes #56.

### LINKED ISSUE #56: toHexString.call not supported in latest driver
via #31 

```
Can I ask why toHexString.call(v) instead of v.toHexString?

toHexString.call(v) is breaking for values of v minted with a later version of the ObjectId class (coming from the MongoDB driver). More recent versions of ObjectId do are not compatible with the toHexString from the version of ObjectId in the version of bson included in this package. Namely:

TypeError: this.id.charCodeAt is not a function
at ObjectID.toHexString (node_modules/bson/lib/bson/objectid.js:74:35)

this.id is now a Buffer and not a string.

Calling v.toHexString will ensure that the version of the toHexString method being called is compatible with the internal data structure of v.
```

### PR DESCRIPTION
**Pull request by rueckstiess**
This change is [Reviewable](https://reviewable.io/reviews/mongodb-js/extended-json/58)

### CODE REVIEW

**Comment by rueckstiess** [comment]
Hm, strange why are the tests not executed anymore?

**Comment by imlucas** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mongodb-js/extended-json/58)*

**Comment by imlucas** [comment]
:lgtm: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/mongodb-js/extended-json/58#-:-KMyhj43oUGTwbNy-zTQ:980077423)*

**Comment by imlucas** [comment]
published in mongodb-extended-json@1.7.0

**Pull request merged**
